jwt:
  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa

server:
  port: 9002

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/eva
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: antifragile

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect


